http:
  port: 8080
admin:
  port: 9876
  host: localhost

apiEndpoints:
  appapi:
    host: localhost
    paths: [ '/api','/api/*' ]
serviceEndpoints:
  appapi:
    url: 'http://loadbalancer/api/'
policies:
  - basic-auth
  - cors
  - expression
  - key-auth
  - log
  - oauth2
  - proxy
  - rate-limit
pipelines:
  default:
    apiEndpoints:
      - appapi
    policies:
      # Uncomment `key-auth:` when instructed to in the Getting Started guide.
      - key-auth:
      - proxy:
          - action:
              serviceEndpoint: appapi
              changeOrigin: true
              prependPath: false
              ignorePath: false
              stripPath: false
