version: '3.8'
services:

  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    networks:
      - parcial
    volumes:
      - mongodb_data:/data/db

  backend:
    build: ./app-back
    container_name: backend
    ports:
      - "3000:3000"
    networks:
      - parcial
    depends_on:
      - mongodb

  frontend:
    build: ./app-front
    container_name: frontend
    ports:
      - "8080:80"  # Mapea el puerto 80 del contenedor Nginx al puerto 8080 del host
    networks:
      - parcial
    depends_on:
      - backend

networks:
  parcial:
    driver: bridge


volumes:
  mongodb_data:
