version: '3.8'
services:

  consul:
    image: consul:1.15
    container_name: consul
    ports:
      - "8500:8500"
      - "8600:8600/udp"
    networks:
      - parcial
    command: agent -server -bootstrap-expect 1 -ui -data-dir /tmp -client=0.0.0.0

  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    networks:
      - parcial
    volumes:
      - mongodb_data:/data/db

  server:
    build: ./app-back
    container_name: server
    ports:
      - "9000:9000"
    environment:
      - CONSUL_HTTP_ADDR=consul:8500
    networks:
      - parcial
    depends_on:
      - consul
      - mongodb

  frontend:
    build: ./app-front
    container_name: frontend
    volumes:
      - ./src:/app/src
    environment:
      - API_URL=http://localhost:9000
    ports:
      - "3000:80"
    networks:
      - parcial
    depends_on:
      - server

networks:
  parcial:
    driver: bridge


volumes:
  mongodb_data:
